seed: 2022
pretrained: False
# dataset parameters
dataset: Crema
Zip_file_path: ./Dataset/Crema.zip  # file path
class_labels: ['neutral', 'happy', 'sad','angry','fearful', 'disgust']
# class_labels: ["positive", "negative", "neutral"]
# class_labels: ["angry", "boredom", "disgust", "fear", "happy", "neutral", "sad"]

# feature parameters
sample_rate: 48000
feature_folder: features/Crema1/ # Crema1 is half dataset

# checkpoints & log files
dataset_path: Output/Crema/  # checkpoint file path
checkpoint_name: Crema_TransOnly_IS1  # checkpoint file name

loss_plot_path: Crema_TransOnly_loss_1
acc_plot_path: Crema_TransOnly_acc_1 # accuracy plot file name
confusion_matrix_path: Crema_TransOnly_confusion_1

# training parameters
feature_exist: False
data_size: 3721
train_ratio: 0.8
val_ratio: 0
test_ratio: 0.2
epochs: 100
batch_size: 64
lr: 0.0001
weight_decay: 0.0001


# Model parameters
rnn_size: 128  # LSTM hidden layer size
# hidden_size: 32 
dropout: 0.1