seed: 2022
pretrained: False
mode: VO
# dataset parameters
dataset: Ravdess
Zip_file_path: ./Dataset/Ravdess_AV.zip  # file path
class_labels: ['neutral', 'happy', 'sad','angry','fearful', 'disgust']
video_features: ["AU01_r" ,"AU02_r" ,"AU04_r" , "AU05_r","AU06_r", "AU07_r", "AU09_r", "AU10_r","AU12_r","AU14_r","AU15_r", "AU17_r", "AU20_r", "AU23_r", "AU25_r", "AU26_r", "AU45_r", "AU01_c", "AU02_c", "AU04_c" ,"AU05_c", "AU06_c", "AU07_c", "AU09_c", "AU10_c", "AU12_c", "AU14_c", "AU15_c", "AU17_c", "AU20_c", "AU23_c", "AU25_c", "AU26_c", "AU28_c", "AU45_c"]

# feature parameters
sample_rate: 48000
feature_folder: features/Ravdess_AV/

# checkpoints & log files
dataset_path: Output/Ravdess_VO/  # checkpoint file path
checkpoint_name: Ravdess_VO_IS1 # checkpoint file name

loss_plot_path: Ravdess_VO_loss1
acc_plot_path: Ravdess_VO_acc1 # accuracy plot file name
confusion_matrix_path: Ravdess_VO_confusion1

# training parameters
feature_exist: True
data_size: None
train_ratio: 0.8
val_ratio: 0
test_ratio: 0.2
epochs: 200
batch_size: 32
lr: 0.0001
weight_decay: 0.0001


# Model parameters
dim_feedforward: 512  
# hidden_size: 32 
dropout: 0.1

# AV:
# Trans only on videos and audios + extracted features
# 1. 0.0001, 0.0001, 512, 0.1, acc = 90.09

# VO:
# Trans only on videos
# 1. 0.0001, 0.0001, 512, 0.1, acc = 83.49